# Generated by Django 4.2.6 on 2024-12-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config_WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whats_app', models.CharField(default='Somente números e sem espaço', max_length=11)),
                ('chave_api_whats_app', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_leads', models.CharField(max_length=50)),
                ('whats_app_leads', models.CharField(max_length=12)),
                ('data_recebimento', models.CharField(max_length=8)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
