# Generated by Django 4.2.6 on 2024-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='data_recebimento',
            field=models.CharField(max_length=16),
        ),
    ]
