# Generated by Django 4.2.6 on 2024-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leads_status_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='data_recebimento',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='leads',
            name='whats_app_leads',
            field=models.CharField(max_length=15),
        ),
    ]
