name: Deploy to Lightsail

on:
  push:
    branches:
      - dev  # Branch monitorada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Fazer checkout do código
      - name: Check out code
        uses: actions/checkout@v3

      # Etapa 2: Configurar SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.LIGHTSAIL_HOST }}" >> ~/.ssh/known_hosts

      # Etapa 3: Deploy no Lightsail
      - name: Deploy to Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -e  # Interrompe em caso de erro
            echo "Iniciando deploy no servidor Lightsail..."

            # Configurações do projeto
            PROJECT_DIR="/home/ubuntu/lp-norden-sao-carlos"
            VENV_DIR="${PROJECT_DIR}/prod-venv"

            # Acessar o diretório do projeto
            cd $PROJECT_DIR

            # Garantir sincronização do repositório
            git fetch origin
            git reset --hard origin/dev

            # Ativar o ambiente virtual e instalar dependências
            source ${VENV_DIR}/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Executar migrações e coletar arquivos estáticos (Django)
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            # Reiniciar serviços (Gunicorn e Nginx) globalmente
            echo "Reiniciando Gunicorn e Nginx..."
            sudo systemctl restart gunicorn  # Gunicorn como serviço do sistema
            sudo systemctl restart nginx     # Nginx como servidor de proxy

            echo "Deploy finalizado com sucesso!"
          EOF
